### ISSUE TITLE
大佬可以参考下vuet

### ISSUE THREAD

**Issue by z-z-k** [masx200/vue-simple-global-state-store-manager#1]
我之前用过几次，但是现在没有维护了

**Comment by masx200** [comment]
集中管理真的好用吗？

那你觉得它哪里好呢？

你的建议是什么呢

> 我之前用过几次，但是现在没有维护了

**Comment by masx200** [comment]
> 我之前用过几次，但是现在没有维护了

# 注意,此代码存储库已被弃用,不会再更新维护了.

# Note that this code repository has been deprecated and will not be updated and maintained.
